vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        pokemons:
            uri_prefix: /upload/images/pokemons
            upload_destination: '%kernel.project_dir%/public/upload/images/pokemons'
